---
# This role installs and sets up keepalived

- name: Install keepalived (debian/ubuntu)
  apt: name=keepalived state=latest
  tags: keepalived
  notify: restart keepalived

- name: Install chk_service shell script
  template:
    src: check_script.sh.j2
    dest: /etc/keepalived/check_script.sh
    mode: 0755
    owner: root
    group: root
  tags: keepalived
  notify: restart keepalived

- name: Setup keepalived configuration
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=started
  tags: keepalived

- name: Flush handlers
  meta: flush_handlers
